### ISSUE TITLE
Unable to find `garment_class_info.pkl` file

### ISSUE THREAD

**Issue by rupang818** [zycliao/TailorNet_dataset#6]
I'm trying to train the TailorNet from scratch, using this dataset, but I'm getting this message, saying that it cannot find the file `garment_class_info.pkl`. Also, the file structure outlined in "Dataset Structure" doesn't seem to be the dataset structure of this repo, but an additional file maybe?
```
start training t-shirt
Warning: log_dir(/Users/jihoonkim/Desktop/UCLA/capstone/TailorNet_logs/tn_baseline/t-shirt_male) already exists
Are you sure continuing? y/ny
Backup code in /Users/jihoonkim/Desktop/UCLA/capstone/TailorNet_logs/tn_baseline/t-shirt_male/code
Traceback (most recent call last):
  File "trainer/base_trainer.py", line 348, in <module>
    main()
  File "trainer/base_trainer.py", line 335, in main
    trainer = Trainer(params)
  File "trainer/base_trainer.py", line 49, in __init__
    self.smpl = SMPL4Garment(gender=self.gender)
  File "/Users/jihoonkim/Desktop/UCLA/capstone/TailorNet/models/smpl4garment.py", line 19, in __init__
    with open(os.path.join(global_var.DATA_DIR, global_var.GAR_INFO_FILE), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jihoonkim/Desktop/UCLA/capstone/TailorNet_data/garment_class_info.pkl'
```

**Comment by zycliao** [comment]
Hi, this file is inside `dataset_meta.zip`. Please download and unzip it.

**Comment by rupang818** [comment]
Thank you
